name: deploy to environment

on:
  workflow_call:
    inputs:
      pathToBicepFile:
        required: true
        type: string
      environmentNamePrefix:
        required: true
        type: string
      environmentType:
        required: true
        type: string
      resourceGroupName:
        required: true
        type: string
      deploymentName:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

permissions:
  id-token: write
  contents: read

jobs:

  validate_inputs_availability:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variableName :
        - pathToBicepFile
        - deploymentName
        - environmentNamePrefix
        - environmentType
        - resourceGroupName
    steps:
      - name: Variable is set and available via job outputs - inputs.${{ matrix.variableName }}
        shell: bash
        run: |
          if [ "${{ inputs[format('{0}', matrix.variableName)] }}" != '' ]; then
            echo "${{ matrix.variableName }} is set";
          else
            echo >&2 "${{ matrix.variableName }} unavailable";
            exit 1
          fi

  validate_secrets_availability:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variableName :
        - AZURE_CLIENT_ID
        - AZURE_TENANT_ID
        - AZURE_SUBSCRIPTION_ID
    steps:
      - name: Variable is set and available via job outputs - secrets.${{ matrix.variableName }}
        shell: bash
        run: |
          if [ "${{ secrets[format('{0}', matrix.variableName)] }}" != '' ]; then
            echo "${{ matrix.variableName }} is set";
          else
            echo >&2 "${{ matrix.variableName }} unavailable";
            exit 1
          fi

  lint:
    name: lint bicep file - ${{ inputs.pathToBicepFile }}
    needs: [validate_inputs_availability, validate_secrets_availability]
    uses: ./.github/workflows/job-lint-bicep.yml
    with:
      pathToBicepFile: ${{ inputs.pathToBicepFile }}

  validate:
    name: validate bicep file for environment - ${{ inputs.environmentType }}
    needs: [validate_inputs_availability, validate_secrets_availability]
    # needs: [lint]
    uses: ./.github/workflows/job-validate-bicep.yml
    with:
      pathToBicepFile: ${{ inputs.pathToBicepFile }}
      environmentType: ${{ inputs.environmentType }}
      resourceGroupName: ${{ inputs.resourceGroupName }}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  preview:
    name: preview (what-if) to ${{ inputs.environmentNamePrefix }} - ${{ inputs.environmentType }}
    needs: [lint, validate]
    uses: ./.github/workflows/job-preview-bicep.yml
    with:
      pathToBicepFile: ${{ inputs.pathToBicepFile }}
      environmentType: ${{ inputs.environmentType }}
      resourceGroupName: ${{ inputs.resourceGroupName }}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  deploy:
    name: deploy to ${{ inputs.environmentNamePrefix }} - ${{ inputs.environmentType }}
    needs: [preview]
    uses: ./.github/workflows/job-deploy.yml
    with:
      pathToBicepFile: ${{ inputs.pathToBicepFile }}
      environmentNamePrefix: ${{ inputs.environmentNamePrefix }}
      environmentType: ${{ inputs.environmentType }}
      resourceGroupName: ${{ inputs.resourceGroupName }}
      deploymentName: ${{ inputs.deploymentName }}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
